@startuml
title Система медицинских компаний Будущее 2.0 диаграмма контейнеров

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml



System(FutureSystem, "Будущее 2.0", "Медицинская компания")


Container_Boundary(FutureSystem, "Future System") {
  System(PortalSystem, "Портал самообслуживания", "Продукты не медицинских данных и интегрированных систем")
  System(MedSystem, "Портал медицинских данных", "Продукты медицинских данных")
  Person(Operator, "Оператор", "Добавляет/получает данные из системы")
  Person(User, "Пользователь данных", "Получает данные, настраивает формат получения")
  Container(OperatorApp, "Клиентский интерфейс оператора", "PowerBuilder", "Позволяет загружать операторам медицинские данные")

  Container(MQ, "Интеграционная шина", "Apache Camel", "Корпоративная шина")
  Container(BI , "BI-система", "Power BI", "Система бизнес анализа полученных данных")
  Container(AL, "ИИ-сервисы", "Python", "ИИ-сервисы для работы с медицинскими данными")
  Container(Fintex, "Финтех-сервисы", "Golang,Java", "Финтех-сервисы в виде отдельной компании с банковской лицензией")
  Container(Pharm, "Фармацевтическая компания", "", "Идентификация клиента, открытие депозита")

  Container(Electronic, "Производитель электроники", "", "Производит электронику для медицинского оборудования")
  Container(Internal, "Внутренние сервисы", "", "Учет внутренних финансовых данных и данных клиентов")
   Container_Boundary(MedSystem, "DataMesh") {
   ContainerDb(MedDWH, "Медицинские данные", "MSSQL", "Хранит медицинские данные системы")
   ContainerDb(ALDWH, "Данные ИИ", "MSSQL", "Хранит настройки ИИ, необходимые для обработки медицинских данных")
   }
   Container_Boundary(PortalSystem, "DataMesh") {
   ContainerDb(FinData, "Финансовые данные", "PosgreSQL", "Данные банка и прочих финансовых систем")
   ContainerDb(ClientData, "Клиентские данные", "PosgreSQL", "Данные клиентов компании")
   ContainerDb(PharmData, "Фармацевтические данные", "PosgreSQL", "Данные фармацевтических компаний")
   ContainerDb(ElectronicData, "Данные производителя электроники", "PosgreSQL", "Данные производителя электроники")
   }


}


Rel(Operator, OperatorApp, "Медицинские данные, снимки")
Rel(OperatorApp, MedSystem, "Медицинские данные, снимки")
Rel(Operator, Internal, "Данные клиентов")
Rel(Operator, Fintex, "Данные клиентов")
Rel(MQ,MedSystem, "Передача медицинских данных")
Rel(Electronic, MQ, "Передача данных производителя электроники")
Rel(Pharm, MQ, "Передача данных фармацевтических компаний")
Rel(PortalSystem, BI, "Передача запрашиваемых срезов данных")
Rel(MQ, PortalSystem, "Передача не медицинских данных")
Rel(MedSystem, BI, "Получения среза медицинских данных")
Rel(AL, MedSystem, "Получения среза медицинских данных")
Rel(BI,User , "Получения среза данных")
Rel(Internal, PortalSystem , "Получения среза данных")
Rel(Fintex, PortalSystem , "Получения среза данных")





@enduml